# Generated by Django 3.2.6 on 2021-08-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
