# Generated by Django 3.2.6 on 2021-08-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_todos_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='file',
            field=models.FileField(max_length=255, null=True, upload_to=''),
        ),
    ]
